name: Post Gospel to Evzo Facebook Pages

# Schedule the workflow to run at 3 AM UTC daily
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: # allows manual trigger too

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # widely used OpenJDK
          java-version: '17'

      # Step 3: Run the JAR
      - name: Run AutoAiay JAR
        run: |
          # echo "Posting to Arabic."
          # java -cp AutoAiay.jar facebook.FbPostEvzoArabic
          # sleep 30
          # echo "Posting to Greek."
          # java -cp AutoAiay.jar facebook.FbPostEvzoGreekGR
          # sleep 30
          # echo "Posting to French."
          # java -cp AutoAiay.jar facebook.FbPostEvzoFrench
          # sleep 30
          # echo "Posting to French Per Ipsum."
          # java -cp AutoAiay.jar facebook.FbPostEvzoPerIpsumFrench
          # sleep 30
          # echo "Posting to German."
          # java -cp AutoAiay.jar facebook.FbPostEvzoGermanDE
          # sleep 30
          # echo "Posting to Netherlands."
          # java -cp AutoAiay.jar facebook.FbPostEvzoNL
          # sleep 30
          # echo "Posting to Italy."
          # java -cp AutoAiay.jar facebook.FbPostEvzoItaly
          # sleep 30
          # echo "Posting to FbPostEvzoItalyAmbrosiano."
          # java -cp AutoAiay.jar facebook.FbPostEvzoItalyAmbrosiano
          # sleep 30
          # echo "Posting to Spanish."
          # java -cp AutoAiay.jar facebook.FbPostEvzoSpanishSP
          # sleep 30
          echo "Posting to Polish."
          java -cp AutoAiay.jar facebook.FbPostEvzoPolishPL
          sleep 30
          echo "Posting to Irish."
          java -cp AutoAiay.jar facebook.FbPostEvzoIreland
          sleep 30
          echo "Posting to Portuguese."
          java -cp AutoAiay.jar facebook.FbPostEvzoPortuguesePT
          sleep 30
          echo "Posting to Armenian."
          java -cp AutoAiay.jar facebook.FbPostEvzoArmenianARM
          sleep 30
          echo "Posting to Malagasy."
          java -cp AutoAiay.jar facebook.FbPostEvzoMalagasy
          sleep 30
          echo "Posting to Turkish."
          java -cp AutoAiay.jar facebook.FbPostEvzoTurkish
          sleep 30
          echo "Posting to Hebrew."
          java -cp AutoAiay.jar facebook.FbPostEvzoHebrew
          sleep 30
          echo "Posting to Russia."
          java -cp AutoAiay.jar facebook.FbPostEvzoRussian
