name: Post Gospel to Evzo Facebook Pages ASIA

# Schedule the workflow to run at 3 AM UTC daily
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: # allows manual trigger too

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # widely used OpenJDK
          java-version: '17'

      # Step 3: Run the JAR
      - name: Run AutoAiay JAR
        run: |
          echo "Posting to China."
          java -cp AutoAiay.jar facebook.FbPostEvzoChinese
          sleep 10
          echo "Posting to Korea."
          java -cp AutoAiay.jar facebook..FbPostEvzoKorean
